### ISSUE TITLE
官网上的玩家都是真的吗？

### ISSUE THREAD

**Issue by everwar2017gmail** [geektcp/Warmane#8]
我看到warmane官网  https://warmane.cn 上面很多玩家的截图，不知道是不是真的？

![image](https://github.com/geektcp/Warmane/assets/147908114/d75221f2-3fd8-4cb1-ad15-8d7c17f162ec)

**Comment by geektcp** [comment]
本服务器不靠玩家人数去宣传，不吹牛。官网是数字是之前的。进游戏看不到玩家数量的。
